# Generated by Django 5.2.7 on 2026-01-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_home_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_page',
            new_name='Hometext',
        ),
    ]
