# Generated by Django 5.2.7 on 2026-01-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_home_page_hometext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometext',
            old_name='name',
            new_name='title',
        ),
    ]
